# Site Info
title:              "Matt Ballas"
description:        "Byte sized posts about math and computer science."
google_verify:      abc123 # Put your Google Verification here
google_analytics:   UA-123

# Author Info
author_name:        "Matt Ballas" # Your name here
author_email:       ballasmatthew@gmail.com # Your email here
author_gravatar:    93571a3c79c7a968bb7c72239d953397 # Your Gravatar md5 hash here for logo

# Site Settings
domain:             mblls.github.io  # Change to your site
url:                https://mblls.github.io
permalink:          /posts/:title # Post permalink
timezone:           America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins:
  - jekyll-sitemap


defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
